version: "3.8"

services:
  frontend:
    build:
      context: ./client
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - './client:/app'
    command: /bin/sh -c "yarn serve"