name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Unit test
        run: yarn test:unit        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  